preload = /home/retoran/Pictures/backgrounds/lucyBackgrounds/lucyIllustration.png
preload = /home/retoran/Pictures/backgrounds/lucyBackgrounds/lucy_portrait.png
preload = /home/retoran/Pictures/backgrounds/lucyBackgrounds/lucy_final_8000x4500px.png
wallpaper = eDP-1,/home/retoran/Pictures/backgrounds/lucyBackgrounds/lucyIllustration.png
splash = false
ipc = off
