# vim: filetype=hyprlang

# Meant to be fractional scaling, but that doesn't work.
monitor=eDP-1,1920x1080@60,0x0,1
monitor=,preferred,auto,auto

# Set primary monitor using xrandr.
exec-once = xrandr --output eDP-1 --primary

xwayland {
  # Might want to force nearest instead of 1
  #force_zero_scaling = true
}

workspace=1,monitor:DP-1
workspace=2,monitor:DP-1
workspace=3,monitor:DP-1
workspace=4,monitor:DP-1
workspace=5,monitor:DP-1
