# vim: filetype=hyprlang

# Terminal
bind = $mainMod, Q, exec, $exec $term
bind = SUPER_SHIFT, Q, exec, $exec $term --class floating
# Thunar
bind = $mainMod, E, exec, $exec $file
# Launcher
bind = $mainMod, R, exec, rofi -show drun -run-command "uwsm app -- {cmd}"
# Rofi window finder
bind = $mainMod, S, exec, $exec rofi -show window
# Task manager
bind = CTRL_SHIFT, escape,exec, $exec $taskmngr
# Screenshotting
bind = ,Print, exec, grim -g "$(slurp)" | wl-copy && notify-send Grim "Snapped Segment"
bind = CTRL,Print, exec, grim -o "$(hyprctl monitors -j | jaq -r '.[] | select(.focused).name')" | wl-copy && notify-send Grim "Snapped Monitor"

bind = $mainMod, A, exec, ~/.config/hypr/scripts/jpOCR.sh

# Gamemode toggle
bind = $mainMod, N, exec, ~/.config/hypr/scripts/hyprGamemode.sh
# Bluetooth connect
bind = $mainMod, B, exec, bluetoothctl connect $BT_HEADPHONE
bind = SUPER_SHIFT, B, exec, bluetoothctl disconnect
# Causing crashes in UWSM for some godforsaken reason
