# vim: filetype=hyprlang

$playerctlPrio=playerctl --player=mpv,%any,chromium,firefox

bind = ,XF86AudioPlay, exec, $playerctlPrio play-pause
bind = ,XF86AudioPrev, exec, $playerctlPrio previous
bind = ,XF86AudioNext, exec, $playerctlPrio next
# Relies on wireplumber
binde = , XF86AudioRaiseVolume, exec, wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 1%+
binde = , XF86AudioLowerVolume, exec, wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 1%-
bind = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
