# vim: filetype=hyprlang

$playerctlPrio=playerctl --player=mpv,%any,chromium,firefox

# TODO: mpris-proxy doesn't seem to obey the same order as these keybinds.
#       mpris-proxy isn't needed for WH1000XM4 because it can send mediakeys directly.
#       When mpris-proxy is active, it targets the first application.
#       There's a playerctld mpris application as well, which might behave as expected if mrpis-proxy targetted it.
#       All a bit of a mess, ideally I'd want to make my own playerctl adjacent thing to fix this.

bind = ,XF86AudioPlay, exec, $playerctlPrio play-pause
bind = ,XF86AudioPause, exec, $playerctlPrio play-pause
bind = ,XF86AudioStop, exec, $playerctlPrio stop
bind = ,XF86AudioPrev, exec, $playerctlPrio previous
bind = ,XF86AudioNext, exec, $playerctlPrio next
# Relies on wireplumber
binde = , XF86AudioRaiseVolume, exec, wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 1%+
binde = , XF86AudioLowerVolume, exec, wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 1%-
bind = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
