# vim: filetype=hyprlang

# Any class marked as "floating" will be floated.
windowrule = match:class floating, float on
# Make any video game float
#windowrule = match:content game, float on, center on
# Make waydroid float
windowrule = match:class ^(w|W)aydroid.*, float on, size 720 1280
# Steam
windowrule = match:initial_class ^((S|s)team|vrmonitor|vrwebhelper)$, float on
windowrule = match:initial_class ^(S|s)team$, match:title ^Steam$, float off, workspace $GAMEWORKSPACE
# Thunar
windowrule = match:class ^thunar$, float on
# This doesn't seem to work, but also it never worked.
windowrule = match:class ^thunar$, match:title - Thunar$, float off
# XArchiver
#windowrulev2 = float, class:^xarchiver$
# Polkit
#windowrulev2 = float, class:^org\.kde\.polkit-kde-authentication-agent-1$
# Kde file selector
#windowrulev2 = float, class:^org.freedesktop.impl.portal.desktop.kde$
#windowrulev2 = center, class:^org.freedesktop.impl.portal.desktop.kde$
#windowrulev2 = size 1000 700, class:^org.freedesktop.impl.portal.desktop.kde$
## Krita file selectors
#windowrulev2 = size 1000 700, class:^krita$,title:- Krita
# GTK File chooser
#windowrulev2 = float, initialTitle:^(Save\ As|Open\ Files)$
#windowrulev2 = size 1000 700, initialTitle:^(Save\ As|Open\ Files)$
#windowrulev2 = center, initialTitle:^(Save\ As|Open\ Files)$
#windowrulev2 = center, initialClass:^xdg-desktop-portal-gtk$
#windowrulev2 = float, initialClass:^xdg-desktop-portal-gtk$
# iwgtk
#windowrule = match:class .*iwgtk$, float on
# Blueman
#windowrule = match:class ^blueman-manager$, float on
# Godot rules
#windowrule = match:class ^Godot$, float on
#windowrule = match:class ^Godot$, match:title - Godot Engine$, float off
# Zenity (Winetricks GUI)
#windowrule = match:class ^zenity$, float on, center on
# Yad (Protontricks GUI)
#windowrule = match:class ^yad$, float on, center on
# Pavucontrol
#windowrule = match:class ^org\.pulseaudio\.pavucontrol$, float on, center on
# Warframe launcher
#windowrule = match:class ^launcher\.exe$, float on, center on
