# vim: filetype=hyprlang

# Lutris
#windowrulev2 = workspace $GAMEWORKSPACE, class:^lutris$
# General games
#windowrulev2 = workspace $GAMEWORKSPACE, content:game
# Discord
#windowrulev2 = workspace $DP2WORKSPACE, class:^(WebCord|VencordDesktop|vesktop)$
# Youtube Music
#windowrulev2 = workspace $DP2WORKSPACE, class:^Youtube Music$
# OpenRGB
#windowrulev2 = workspace $DP1WORKSPACE, class:^openrgb$
