#!/usr/bin/nft -f
# vim:set ts=2 sw=2 et:

table inet filter {
  chain input_accepts {
    tcp dport 25565 accept comment "allow TCP minecraft"
    udp dport 25565 accept comment "allow UDP minecraft"
  }
}
