#!/usr/bin/nft - f
# vim:set ts=2 sw=2 et:

define passthrough_inner_ip = 10.100.100.33

table inet filter {
	chain forward_accepts {
		# forward all packets that are already part of a connection to our passthrough
		ct state vmap { invalid: drop, established : accept, related : accept }
		# forward all packets originating from network namespace "passthrough"
		ip saddr $passthrough_inner_ip accept
    # forward all packets sent to TCP port 8080 of the "passthrough" net

	}
}
table inet nat {
	chain postrouting {
		# masquerade all packets originating from network namespace "passthrough"
		ip saddr $passthrough_inner_ip masquerade
	}
  #chain prerouting {
    #type nat hook prerouting priority -100; policy accept
    # passthrough 1024-49151 ports to our network.
    # we should be more selective with this but oh well I just want it to work for now.
    #tcp dport 1024-49151 accept 
  #}
}
