# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "ahci"
    "xhci_pci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [
    "kvm-amd"
    "dcrypt"
  ];
  boot.extraModulePackages = [ ];

  # File systems
  fileSystems."/" = {
    device = "/dev/mapper/root";
    fsType = "btrfs";
  };

  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/12fc0ea1-09ad-4d89-b77b-6b4a1b57286e";
  environment.etc."crypttab".text = ''
    raidn0_0 /dev/disk/by-uuid/f84d1c39-7d03-486b-b2bb-7a073d0bfa3b /etc/cryptkey
    raidn0_1 /dev/disk/by-uuid/9a976daf-3d19-43b1-8a0a-cb9a92e2c0ca /etc/cryptkey
    raidn0_2 /dev/disk/by-uuid/fc993da8-0957-4d24-a543-e77d8b01ef48 /etc/cryptkey
  '';
  fileSystems."/mnt/raidn0" = {
    # TODO: Should go by mapper UUID instead, that's more correct.
    device = "/dev/disk/by-uuid/465ce5a8-ed17-4c4e-8bf9-2ef10ced35c5";
    fsType = "btrfs";
    # There should also be some other mount options we use for this.
    options = [
      "compress=zstd"
      # Make it appear in GVFS
      "x-gvfs-show"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/2611-2EA3";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    {
      device = "/swap/swapfile";
      size = 64 * 1024;
    }
  ];

  hardware.amdgpu.opencl.enable = true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
