[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#7c8f8f"
blue = "#82aaff"
cyan = "#7fdbca"
green = "#21c7a8"
magenta = "#ae81ff"
red = "#ff5874"
white = "#d6deeb"
yellow = "#ecc48d"

[colors.cursor]
cursor = "#9ca1aa"
text = "#080808"

[colors.normal]
black = "#1d3b53"
blue = "#82aaff"
cyan = "#7fdbca"
green = "#a1cd5e"
magenta = "#c792ea"
red = "#fc514e"
white = "#a1aab8"
yellow = "#e3d18a"

[colors.primary]
background = "#0D0F1C"
bright_foreground = "#eeeeee"
foreground = "#acb4c2"

[colors.selection]
background = "#b2ceee"
text = "#080808"

[cursor]
blink_interval = 500
blink_timeout = 0
thickness = 0.15
unfocused_hollow = false

[cursor.style]
blinking = "on"
shape = "Underline"

[cursor.vi_mode_style]
blinking = "on"
shape = "Underline"

[font]
size = 13.0

[font.normal]
family = "IosevkaTerm NF"
style = "Regular"

[shell]
program = "/bin/zsh"

[window]
opacity = 0.8
