#!/bin/zsh
if [[ $1 == "hypr" ]]; then
  source ~/.scripts/hypr/hyprLaunch.zsh
elif [[ $1 == "sway" ]]; then
  source ~/.scripts/sway/swayLaunch.zsh
elif [[ $1 == "plasma" ]]; then
  startplasma-wayland
else
  echo "None selected!"
fi

