#!/bin/zsh
echo "Calling nvim mason upgrade."
nvim --headless -c "autocmd User MasonUpgradeComplete sleep 100m | qall" -c 'MasonUpgrade'
echo "Calling waydroid upgrade"
sudo waydroid upgrade
echo "Calling paru"
paru
echo "Finished!"
